//! This code was autogenerated with `dbus-codegen-rust -d org.mpris.MediaPlayer2.rhythmbox -p /org/gnome/UPnP/MediaServer2/Playlists`, see https://github.com/diwic/dbus-rs
use dbus as dbus;
#[allow(unused_imports)]
use dbus::arg;
use dbus::blocking;

pub trait OrgFreedesktopDBusProperties {
    fn get(&self, interface_name: &str, property_name: &str) -> Result<arg::Variant<Box<dyn arg::RefArg + 'static>>, dbus::Error>;
    fn get_all(&self, interface_name: &str) -> Result<arg::PropMap, dbus::Error>;
    fn set(&self, interface_name: &str, property_name: &str, value: arg::Variant<Box<dyn arg::RefArg>>) -> Result<(), dbus::Error>;
}

#[derive(Debug)]
pub struct OrgFreedesktopDBusPropertiesPropertiesChanged {
    pub interface_name: String,
    pub changed_properties: arg::PropMap,
    pub invalidated_properties: Vec<String>,
}

impl arg::AppendAll for OrgFreedesktopDBusPropertiesPropertiesChanged {
    fn append(&self, i: &mut arg::IterAppend) {
        arg::RefArg::append(&self.interface_name, i);
        arg::RefArg::append(&self.changed_properties, i);
        arg::RefArg::append(&self.invalidated_properties, i);
    }
}

impl arg::ReadAll for OrgFreedesktopDBusPropertiesPropertiesChanged {
    fn read(i: &mut arg::Iter) -> Result<Self, arg::TypeMismatchError> {
        Ok(OrgFreedesktopDBusPropertiesPropertiesChanged {
            interface_name: i.read()?,
            changed_properties: i.read()?,
            invalidated_properties: i.read()?,
        })
    }
}

impl dbus::message::SignalArgs for OrgFreedesktopDBusPropertiesPropertiesChanged {
    const NAME: &'static str = "PropertiesChanged";
    const INTERFACE: &'static str = "org.freedesktop.DBus.Properties";
}

impl<'a, T: blocking::BlockingSender, C: ::std::ops::Deref<Target=T>> OrgFreedesktopDBusProperties for blocking::Proxy<'a, C> {

    fn get(&self, interface_name: &str, property_name: &str) -> Result<arg::Variant<Box<dyn arg::RefArg + 'static>>, dbus::Error> {
        self.method_call("org.freedesktop.DBus.Properties", "Get", (interface_name, property_name, ))
            .and_then(|r: (arg::Variant<Box<dyn arg::RefArg + 'static>>, )| Ok(r.0, ))
    }

    fn get_all(&self, interface_name: &str) -> Result<arg::PropMap, dbus::Error> {
        self.method_call("org.freedesktop.DBus.Properties", "GetAll", (interface_name, ))
            .and_then(|r: (arg::PropMap, )| Ok(r.0, ))
    }

    fn set(&self, interface_name: &str, property_name: &str, value: arg::Variant<Box<dyn arg::RefArg>>) -> Result<(), dbus::Error> {
        self.method_call("org.freedesktop.DBus.Properties", "Set", (interface_name, property_name, value, ))
    }
}

pub trait OrgFreedesktopDBusIntrospectable {
    fn introspect(&self) -> Result<String, dbus::Error>;
}

impl<'a, T: blocking::BlockingSender, C: ::std::ops::Deref<Target=T>> OrgFreedesktopDBusIntrospectable for blocking::Proxy<'a, C> {

    fn introspect(&self) -> Result<String, dbus::Error> {
        self.method_call("org.freedesktop.DBus.Introspectable", "Introspect", ())
            .and_then(|r: (String, )| Ok(r.0, ))
    }
}

pub trait OrgFreedesktopDBusPeer {
    fn ping(&self) -> Result<(), dbus::Error>;
    fn get_machine_id(&self) -> Result<String, dbus::Error>;
}

impl<'a, T: blocking::BlockingSender, C: ::std::ops::Deref<Target=T>> OrgFreedesktopDBusPeer for blocking::Proxy<'a, C> {

    fn ping(&self) -> Result<(), dbus::Error> {
        self.method_call("org.freedesktop.DBus.Peer", "Ping", ())
    }

    fn get_machine_id(&self) -> Result<String, dbus::Error> {
        self.method_call("org.freedesktop.DBus.Peer", "GetMachineId", ())
            .and_then(|r: (String, )| Ok(r.0, ))
    }
}

pub trait OrgGnomeUPnPMediaObject2 {
    fn parent(&self) -> Result<dbus::Path<'static>, dbus::Error>;
    fn type_(&self) -> Result<String, dbus::Error>;
    fn path(&self) -> Result<String, dbus::Error>;
    fn display_name(&self) -> Result<String, dbus::Error>;
}

impl<'a, T: blocking::BlockingSender, C: ::std::ops::Deref<Target=T>> OrgGnomeUPnPMediaObject2 for blocking::Proxy<'a, C> {

    fn parent(&self) -> Result<dbus::Path<'static>, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.gnome.UPnP.MediaObject2", "Parent")
    }

    fn type_(&self) -> Result<String, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.gnome.UPnP.MediaObject2", "Type")
    }

    fn path(&self) -> Result<String, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.gnome.UPnP.MediaObject2", "Path")
    }

    fn display_name(&self) -> Result<String, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.gnome.UPnP.MediaObject2", "DisplayName")
    }
}

pub trait OrgGnomeUPnPMediaContainer2 {
    fn list_children(&self, offset: u32, max: u32, filter: Vec<&str>) -> Result<Vec<arg::PropMap>, dbus::Error>;
    fn list_containers(&self, offset: u32, max: u32, filter: Vec<&str>) -> Result<Vec<arg::PropMap>, dbus::Error>;
    fn list_items(&self, offset: u32, max: u32, filter: Vec<&str>) -> Result<Vec<arg::PropMap>, dbus::Error>;
    fn search_objects(&self, query: &str, offset: u32, max: u32, filter: Vec<&str>) -> Result<Vec<arg::PropMap>, dbus::Error>;
    fn child_count(&self) -> Result<u32, dbus::Error>;
    fn item_count(&self) -> Result<u32, dbus::Error>;
    fn container_count(&self) -> Result<u32, dbus::Error>;
    fn searchable(&self) -> Result<bool, dbus::Error>;
    fn icon(&self) -> Result<dbus::Path<'static>, dbus::Error>;
}

#[derive(Debug)]
pub struct OrgGnomeUPnPMediaContainer2Updated {
}

impl arg::AppendAll for OrgGnomeUPnPMediaContainer2Updated {
    fn append(&self, _: &mut arg::IterAppend) {
    }
}

impl arg::ReadAll for OrgGnomeUPnPMediaContainer2Updated {
    fn read(_: &mut arg::Iter) -> Result<Self, arg::TypeMismatchError> {
        Ok(OrgGnomeUPnPMediaContainer2Updated {
        })
    }
}

impl dbus::message::SignalArgs for OrgGnomeUPnPMediaContainer2Updated {
    const NAME: &'static str = "Updated";
    const INTERFACE: &'static str = "org.gnome.UPnP.MediaContainer2";
}

impl<'a, T: blocking::BlockingSender, C: ::std::ops::Deref<Target=T>> OrgGnomeUPnPMediaContainer2 for blocking::Proxy<'a, C> {

    fn list_children(&self, offset: u32, max: u32, filter: Vec<&str>) -> Result<Vec<arg::PropMap>, dbus::Error> {
        self.method_call("org.gnome.UPnP.MediaContainer2", "ListChildren", (offset, max, filter, ))
            .and_then(|r: (Vec<arg::PropMap>, )| Ok(r.0, ))
    }

    fn list_containers(&self, offset: u32, max: u32, filter: Vec<&str>) -> Result<Vec<arg::PropMap>, dbus::Error> {
        self.method_call("org.gnome.UPnP.MediaContainer2", "ListContainers", (offset, max, filter, ))
            .and_then(|r: (Vec<arg::PropMap>, )| Ok(r.0, ))
    }

    fn list_items(&self, offset: u32, max: u32, filter: Vec<&str>) -> Result<Vec<arg::PropMap>, dbus::Error> {
        self.method_call("org.gnome.UPnP.MediaContainer2", "ListItems", (offset, max, filter, ))
            .and_then(|r: (Vec<arg::PropMap>, )| Ok(r.0, ))
    }

    fn search_objects(&self, query: &str, offset: u32, max: u32, filter: Vec<&str>) -> Result<Vec<arg::PropMap>, dbus::Error> {
        self.method_call("org.gnome.UPnP.MediaContainer2", "SearchObjects", (query, offset, max, filter, ))
            .and_then(|r: (Vec<arg::PropMap>, )| Ok(r.0, ))
    }

    fn child_count(&self) -> Result<u32, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.gnome.UPnP.MediaContainer2", "ChildCount")
    }

    fn item_count(&self) -> Result<u32, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.gnome.UPnP.MediaContainer2", "ItemCount")
    }

    fn container_count(&self) -> Result<u32, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.gnome.UPnP.MediaContainer2", "ContainerCount")
    }

    fn searchable(&self) -> Result<bool, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.gnome.UPnP.MediaContainer2", "Searchable")
    }

    fn icon(&self) -> Result<dbus::Path<'static>, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(self, "org.gnome.UPnP.MediaContainer2", "Icon")
    }
}
